<?php
use EenmaalAndermaal\App;
use EenmaalAndermaal\Services\GetService;
use EenmaalAndermaal\View\Component\FilterComponent;

/** @var FilterComponent $this */
$baseUrl = App::getApp()->getConfig()->get('website.url');
$get = GetService::getInstance();
?>
<div class="filter-component">
    <h3>Filter</h3>
    <div class="row">
        <form class="hide-on-med-and-down">
            <?= $get->createHiddenInputs(["minPrijs", "maxPrijs", "postcode", "maxAfstand"]) ?>
            <div class="col s12">
                <p><b>Prijs</b></p>
            </div>
            <div class="input-field col s6">
                <input id="minPrijs1" type="number" class="validate quantity" min="0"
                       value="<?= $get->getVar("minPrijs") ?>"
                       name="minPrijs">
                <label for="minPrijs1">Minprijs</label>
            </div>
            <div class="input-field col s6">
                <input id="maxPrijs1" type="number" class="validate quantity" min="1"
                       value="<?= $get->getVar("maxPrijs") ?>"
                       name="maxPrijs">
                <label for="maxPrijs1">Maxprijs</label>
            </div>
            <div class="col s12">
                <p><b>Afstand</b></p>
            </div>
            <div class="input-field col s6 no-margin">
                <input type="text" name="postcode" maxlength="32" id="search_zipcode" placeholder="Postcode"
                       value="<?= $get->getVar("postcode") ?>">
                <label for="search_zipcode"></label>
            </div>
            <div class="input-field col s6 no-margin">
                <select name="maxAfstand" id="">
                    <option value="-1"  <?= in_array($get->getVar("maxAfstand"), [false, -1, null, '']) ? "selected" : "" ?>>Elke afstand</option>
                    <option value="5"  <?= $get->getVar("maxAfstand") == 5 ? "selected" : "" ?>>5km</option>
                    <option value="10" <?= $get->getVar("maxAfstand") == 10 ? "selected" : "" ?>>10km</option>
                    <option value="25" <?= $get->getVar("maxAfstand") == 25 ? "selected" : "" ?>>25km</option>
                    <option value="35" <?= $get->getVar("maxAfstand") == 35 ? "selected" : "" ?>>35km</option>
                    <option value="50" <?= $get->getVar("maxAfstand") == 50 ? "selected" : "" ?>>50km</option>
                    <option value="75" <?= $get->getVar("maxAfstand") == 75 ? "selected" : "" ?>>75km</option>
                    <option value="100" <?= $get->getVar("maxAfstand") == 100 ? "selected" : "" ?>>100km</option>
                </select>
            </div>
            <div class="col s12 right-align">
                <input value="Filter" class="btn light-green" type="submit">
            </div>
        </form>
        <form method="get" class="hide-on-large-only">
            <?= $get->createHiddenInputs(["minPrijs", "maxPrijs", "postcode", "maxAfstand"]) ?>
            <div class="col s12">
                <p><b>Prijs</b></p>
            </div>
            <div class="input-field col s12">
                <input id="minPrijs2" type="number" class="validate quantity" min="0"
                       value="<?= $get->getVar("minPrijs") ?>"
                       name="minPrijs">
                <label for="minPrijs2">Minprijs</label>
            </div>
            <div class="input-field col s12">
                <input id="maxPrijs2" type="number" class="validate quantity" min="1"
                       value="<?= $get->getVar("maxPrijs") ?>"
                       name="maxPrijs">
                <label for="maxPrijs2">Maxprijs</label>
            </div>
            <div class="col s12">
                <p><b>Afstand</b></p>
            </div>
            <div class="input-field col s12">
                <input type="text" name="afstand" maxlength="32" id="search_zipcode" placeholder="Postcode"
                       value="<?= $get->getVar("postcode") ?>">
                <label for="search_zipcode"></label>
            </div>
            <div class="input-field col s12">
                <select name="maxAfstand" id="">
                    <option value="-1"  <?= in_array($get->getVar("maxAfstand"), [false, -1, null, '']) ? "selected" : "" ?>>Elke afstand</option>
                    <option value="5"  <?= $get->getVar("maxAfstand") == 5 ? "selected" : "" ?>>5km</option>
                    <option value="10" <?= $get->getVar("maxAfstand") == 10 ? "selected" : "" ?>>10km</option>
                    <option value="25" <?= $get->getVar("maxAfstand") == 25 ? "selected" : "" ?>>25km</option>
                    <option value="35" <?= $get->getVar("maxAfstand") == 35 ? "selected" : "" ?>>35km</option>
                    <option value="50" <?= $get->getVar("maxAfstand") == 50 ? "selected" : "" ?>>50km</option>
                    <option value="75" <?= $get->getVar("maxAfstand") == 75 ? "selected" : "" ?>>75km</option>
                    <option value="100" <?= $get->getVar("maxAfstand") == 100 ? "selected" : "" ?>>100km</option>
                </select>
            </div>
        </form>
    </div>
</div>