<?php

use EenmaalAndermaal\App;
use EenmaalAndermaal\Model\RubriekModel;
use EenmaalAndermaal\Services\GetService;
use EenmaalAndermaal\View\Component\SearchbarComponent;

/** @var $this SearchbarComponent */
$get = GetService::getInstance();
$url = App::getApp()->getConfig()->get("website.url");
?>
<form action="<?= $url ?>zoekresultaat" method="get" id="searchbar" class="row no-margin">
    <?= $get->createHiddenInputs(["zoeken", "rubriek", "postcode", "maxAfstand"]) ?>
    <div class="input-field no-margin col l3 m6 s12">
        <i class="material-icons prefix">search</i>
        <input name="zoeken" type="text" id="zoeken" placeholder="Zoeken"
            value="<?= $get->getVar("zoeken") ?>">
        <label for="zoeken"></label>
    </div>
    <div class="input-field no-margin col l3 m6 s12">
        <select name="rubriek" id="search_cat_select">
            <option value="-1" <?= in_array($get->getVar("rubriek"), [false, -1, null, '']) ? "selected" : "" ?>>Alle rubrieken</option>
            <?php foreach ($this->collection as $rubriek) {
                /** @var RubriekModel $rubriek */
                ?>
                <optgroup label="<?= $rubriek->naam ?>">
                    <?php foreach ($rubriek->getChildren() as $sub) { ?>
                        <option value="<?= $sub->getIdentifier() ?>"
                            <?= $get->getVar("rubriek") == $sub->getIdentifier() ? "selected" : "" ?>><?= $sub->naam ?></option>
                    <?php } ?>
                </optgroup>
            <?php } ?>
        </select>
        <label for="search_cat_select"></label>
    </div>
    <div class="col l6 m12 s12 no-margin">
        <div class="row no-margin">
            <div class="input-field col l4 m4 s4 no-margin">
                <input name="postcode" type="text" maxlength="32" id="search_zipcode" placeholder="Postcode"
                       value="<?= $get->getVar("postcode") ?>">
                <label for="search_zipcode"></label>
            </div>
            <div class="input-field col l5 m5 s5 no-margin">
                <select name="maxAfstand" id="">
                    <option value="-1"  <?= in_array($get->getVar("maxAfstand"), [false, -1, null, '']) ? "selected" : "" ?>>Elke afstand</option>
                    <option value="5"  <?= $get->getVar("maxAfstand") == 5 ? "selected" : "" ?>>5km</option>
                    <option value="10" <?= $get->getVar("maxAfstand") == 10 ? "selected" : "" ?>>10km</option>
                    <option value="25" <?= $get->getVar("maxAfstand") == 25 ? "selected" : "" ?>>25km</option>
                    <option value="35" <?= $get->getVar("maxAfstand") == 35 ? "selected" : "" ?>>35km</option>
                    <option value="50" <?= $get->getVar("maxAfstand") == 50 ? "selected" : "" ?>>50km</option>
                    <option value="75" <?= $get->getVar("maxAfstand") == 75 ? "selected" : "" ?>>75km</option>
                    <option value="100" <?= $get->getVar("maxAfstand") == 100 ? "selected" : "" ?>>100km</option>
                </select>
            </div>
            <div class="col input-field l3 m3 s3 no-margin search_submit">
                <input value="Zoek" type="submit" class="btn light-green">
            </div>
        </div>
    </div>
</form>