<?php

use EenmaalAndermaal\View\Component\VeilingComponent;

?>

    <?php
    $counter = 1;

    foreach ($this->collection as $item) { ?>
    <?php if ($counter % 3 == 1) {
    echo "<div class='row'>";
         }?>
        <div class="col s12 m12 l4">
            <?= $this->renderComponent(new VeilingComponent($item)) ?>
        </div>
        <?php
        if ($counter % 3 == 0) {
            echo "</div>";
        }
    $counter++;
    }

    ?>

