<?php
/** @var VeilingComponent $this */

use EenmaalAndermaal\View\Component\VeilingComponent;

?>
    <div class="card">
        <div class="card-image">
            <img src="<?= $this->item->image?>">
        </div>
        <div class="card-content">
            <span class="card-title black-text"><?= $this->item->name?></span>
            <p><?= $this->item->description?></p>
        </div>
        <div class="card-content">
            <p class="veiling-countdown"><?= $this->item->timer?><span class="right">&euro;<?=$this->item->price?></span></p>
        </div>
        <div class="card-action">
            <a class="btn light-green darken-2" href="#">Bekijk veiling</a>
        </div>
    </div>