<div class="container">
    <div class="row">
        <form method="post" class="col s12">
            <div class="row">
                <h1>Wachtwoord vergeten?</h1>
                <p>Weet je het wachtwoord niet meer?
                    Vul hieronder je e-mailadres in.
                    We sturen dan binnen enkele minuten een e-mail waarmee een nieuw wachtwoord kan worden
                    aangemaakt.</p>
                <div class="input-field col s12 m6 l6 ">
                    <input placeholder="Vul hier uw email in" name="email" required id="email" type="email"
                           class="validate">
                    <label for="email">Email</label>
                </div>

            </div>

            <input class="btn light-green margin-bottom-20" type="submit" value="Verzenden">
        </form>

    </div>
</div>