<div class="container ">
    <div class="row">
        <?php if ($this->status) { ?>
            <form class="col s12" method="post">
                <?php if(isset($this->error) && count($this->error)) { ?>
                    <div class="row">
                        <div class="col s12">
                            <div class="card red white-text">
                                <div class="card-content">
                                    <ul>
                                        <?php foreach ($this->error as $error) { ?>
                                            <li><?= $error ?></li>
                                        <?php } ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <div class="row">
                    <h3 class="light-green-text">Kies een nieuw wachtwoord, <?= $this->gebruikersnaam ?></h3>
                    <div class="input-field col s12 m6 l6 ">
                        <input type="hidden" name="gebruikersnaam" value="<?= $this->gebruikersnaam ?>">
                        <input placeholder="wachtwoord" id="newpassword" name="password" type="password" class="validate" minlength="6"
                               required="required">
                        <label for="newpassword">Wachtwoord</label>
                    </div>
                    <div class="input-field col s12 m6 l6 ">
                        <input type="hidden" name="gebruikersnaam" value="<?= $this->gebruikersnaam ?>">
                        <input placeholder="wachtwoord" id="newpassword2" name="password2" type="password" class="validate" minlength="6"
                               required="required">
                        <label for="newpassword2">Wachtwoord herhalen</label>
                    </div>
                </div>
                <input class="btn light-green" type="submit" value="Verzenden">
            </form>
        <?php } else { ?>
            <div class="col s12">
                <h1>Geen verzoek gevonden</h1>
                <p>Vraag eerst een nieuw wachtwoord aan voor jet het wachtwoord kan resetten</p>
            </div>
        <?php } ?>
    </div>
</div>