<div class="container ">
    <form class="col s12">
        <div class="row">
            <h3 class="light-green-text">Kies een nieuw wachtwoord</h3>
            <div class="input-field col s12 m6 l6 ">
                <input placeholder="wachtwoord" id="newpassword" type="password" class="validate" minlength="6" required="required">
                <input placeholder="herhaal wachtwoord" id="newpassword2" type="password" class="validate" minlength="6" required="required">
            </div>
        </div>
        <input class="btn light-green" type="submit" value="Verzenden">
    </form>
</div>