<div class="container">
    <div class="row">
        <div class="col s12">
            <?php if ($this->status) { ?>
                <h1>Success!</h1>
                <p class="flow-text">Email is verstuurd met een link om uw wachtwoord te resetten!</p>
            <?php } else { ?>
                <h1>Fout!</h1>
                <p class="flow-text">Er is geen account met dit emailadres gevonden!</p>
                <a href="<?= \EenmaalAndermaal\App::getApp()->getConfig()->get("website.url") ?>wachtwoord-vergeten">Opnieuw proberen</a>
            <?php } ?>
        </div>
    </div>
</div>