<?php

use EenmaalAndermaal\App;
use EenmaalAndermaal\Model\VeilingModel;
use EenmaalAndermaal\Services\UserService;
use EenmaalAndermaal\Util\StringUtil;

/** @var \EenmaalAndermaal\View\ProfileView $this */
$baseUrl = App::getApp()->getConfig()->get("website.url");
$getUser = \EenmaalAndermaal\Services\UserService::getInstance();

$editable = false;
?>
<div class="container">
    <?php if (UserService::getInstance()->userLoggedIn()) { ?>
        <div class="row">
            <div class="col s12">
                <h1>Profiel</h1>
                <div class="row">
                    <div class="col s12 m4 l4"><img class="responsive-img" src="<?= $baseUrl ?>style/img/bespaar.jpg">
                        <button id="editbtn" class="waves-effect waves-light btn light-green" name="editbtn">
                            <i class="large material-icons right">build</i>Edit
                        </button>
                        <div id="savecancel" name="editbtns" style="display: none">
                            <button id="saveedit" class="waves-effect waves-light btn light-green" name="saveedit">
                                <i class="large material-icons right">save</i>save
                            </button>
                            <button id="canceledit" class="waves-effect waves-light btn red" name="editbtn">
                                <i class="large material-icons right">cancel</i>cancel
                            </button>
                        </div>
                    </div>
                    <div class="col s12 m8 l8">
                        <h4>Gegevens</h4>
                        <b>Gebruikers informatie</b>
                        <div class="divider"></div>
                        <div class="row">
                            <div class="col s6 m6 l6 bold">Gebruikersnaam</div>
                            <div class="col s6 m6 l6"><?= $getUser->getCurrentUsername() ?></div>

                            <div class="col s6 m6 l6 bold">Voornaam</div>
                            <div id="uservalue1" name="uservalue1" class="col s6 m6 l6"><?=
                                $getUser->getCurrentUser()->voornaam ?></div>
                            <div class="col s6 m6 l6 bold">Achternaam</div>
                            <div id="uservalue2" name="uservalue2" class="col s6 m6 l6"><?=
                                $getUser->getCurrentUser()->achternaam ?></div>
                            <div class="col s6 m6 l6 bold">Postcode</div>
                            <div id="uservalue7" name="uservalue7" class="col s6 m6 l6"><?=
                                $getUser->getCurrentUser()->postcode ?></div>
                            <div class="col s6 m6 l6 bold">Adres</div>
                            <div id="uservalue8" name="uservalue8" class="col s6 m6 l6"><?=
                                $getUser->getCurrentUser()->adres ?></div>
                            <div class="col s6 m6 l6 bold">Plaatsnaam</div>
                            <div id="uservalue3" name="uservalue3" class="col s6 m6 l6"><?=
                                $getUser->getCurrentUser()->plaatsnaam ?></div>
                            <div class="col s6 m6 l6 bold">Land</div>
                            <div id="uservalue4" name="uservalue4" class="col s6 m6 l6"><?=
                                $getUser->getCurrentUser()->land ?></div>
                            <div id="dropdown" class="col s6 m6 l6">
                                <select name="land"
                                        id="land"
                                        tabindex="8"
                                        class="validate" required>
                                    <option value="" <?= count($this->fields) ? "" : "selected" ?> disabled>Selecteer
                                        een
                                        land
                                    </option>
                                    <?php foreach ($this->landen as $land) {
                                        /** @var \EenmaalAndermaal\Model\LandModel $land */
                                        ?>
                                        <option value="<?= $land->landcode ?>"
                                            <?= isset($getUser->getCurrentUser()->land) && $land->landcode == $getUser->getCurrentUser()->land ? 'selected' : '' ?>
                                        ><?= $land->naam ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <b>Contact informatie</b>
                        <div class="divider"></div>
                        <div class="row">
                            <div class="col s6 m6 l6 bold">Email</div>
                            <div class="col s6 m6 l6" id="uservalue5" name="uservalue5"><?=
                                $getUser->getCurrentUser()->email ?></div>
                            <div class="col s6 m6 l6 bold">Telefoonnummer</div>
                            <div class="col s6 m6 l6" id="uservalue6" name="uservalue6"><?=
                                $getUser->getCurrentUser()->telefoonnummer ?></div>
                        </div>
                        <b>Status</b>
                        <div class="divider"></div>
                        <div class="row">
                            <div class="col s6 m6 l6 bold">Status</div>
                            <div class="col s6 m6 l6">Verkoper</div>

                        </div>
                    </div>
                </div>

                <?php if (UserService::getInstance()->getCurrentUser()->permissie > 0) { ?>
                <div class="row">
                    <div class="col s12 m4 l3">
                        <h4>Reviews</h4>
                        <div class="col s12 m12 l12">
                            <div class="row">
                                <div class="col s12 m12 l12">Aantal reviews: 5</div>
                                <div class="col s12 m12 l12">Gemiddelde rating: 3.7</div>

                                <div class="col s12 m12 l12">
                                    <b>Meest recente review</b>
                                    <div class="row">
                                        <div class="col s12 m12 l12">
                                            <div class="card white">
                                                <div class="card-content black-text">
                                                    <span class="card-title">Mooi product!</span>
                                                    <b>Door: koper1</b>
                                                    <p>Product is van goed kwaliteit! Het is ook snel geleverd!</p>
                                                    <p class="bold">Rating: 4/5</p>
                                                </div>
                                            </div>
                                            <button class="btn light-green" disabled>Bekijk alle reviews</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col s12 m4 l3">
                        <h4>Mijn veilingen</h4>
                        <ul class="collapsible">
                            <?php foreach ($this->veilingen as $veiling) { ?>
                                <li>
                                    <div class="collapsible-header"><?= $veiling['titel'] ?></div>
                                    <div class="collapsible-body">
                                        <table>
                                            <tbody>
                                            <tr>
                                                <td>Status</td>
                                                <td><?= $veiling['gesloten'] ? "Gesloten" : "Open" ?></td>
                                            </tr>
                                            <tr>
                                                <td>Huidige bod</td>
                                                <td>&euro; <?= $veiling['verkoopPrijs'] / 100 ?></td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <br>
                                        <a href="<?= $baseUrl ?>veiling/<?= $veiling['nummer'] ?>"
                                           class="btn light-green">Ga
                                            naar veiling</a>
                                    </div>

                                </li>


                            <?php } ?>

                        </ul>
                    </div>


                    <?php } ?>

                    <div class="row">

                        <div class="col s12 m4 l3">
                            <h4>Geboden veiling</h4>
                            <ul class="collapsible">
                                <?php foreach ($this->geboden as $veiling) {
                                    $hoogsteBieder = VeilingModel::getHoogsteBieder($veiling['nummer']);
                                    ?>
                                    <li>
                                        <div class="collapsible-header"><?= $veiling['titel'] ?><?php if ($hoogsteBieder != UserService::getInstance()->getCurrentUser()->gebruikersnaam) {
                                                echo "<span class='new badge red'></span>";
                                            } ?></div>
                                        <div class="collapsible-body">
                                            <?php if ($hoogsteBieder != UserService::getInstance()->getCurrentUser()->gebruikersnaam){?>
                                            <div class="card red white-text center-align">
                                                U bent overboden!
                                            </div>
                                            <?php }?>
                                            <table>
                                                <tbody>
                                                <tr>
                                                    <td>Status</td>
                                                    <td><?= $veiling['gesloten'] ? "Gesloten" : "Open" ?></td>
                                                </tr>
                                                <tr>
                                                    <td>Huidige bod</td>
                                                    <td><?= StringUtil::euro($veiling['verkoopPrijs']) ?></td>
                                                </tr>
                                                </tbody>
                                            </table>
                                            <br>
                                            <a href="<?= $baseUrl ?>veiling/<?= $veiling['nummer'] ?>"
                                               class="btn light-green">Ga
                                                naar veiling</a>
                                        </div>

                                    </li>


                                <?php } ?>


                            </ul>
                        </div>

                        <div class="col s12 m4 l3">
                            <h4>Acties</h4>
                            <ul class="profile-buttons">
                                <?php if ($getUser->getCurrentUser()->permissie < 1) { ?>
                                    <li>
                                        <a href="<?= $baseUrl ?>verkoperWorden" class="btn btn-block light-green">
                                            Verkoper worden
                                        </a>
                                    </li>
                                <?php } ?>
                                <li>
                                    <a href="<?= $baseUrl ?>wachtwoord-vergeten" class="btn btn-block light-green">Wachtwoord
                                        vergeten</a>
                                </li>
                                <li>
                                    <a href="<?= $baseUrl ?>verwijder" class="btn btn-block light-green">Verwijder
                                        gegevens</a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } else { ?>
        <h1>U bent niet ingelogd</h1>
        <p>U hebt geen toegang tot deze pagina. <a href="<?= $baseUrl ?>login">Klik hier om in te loggen</a></p>
    <?php } ?>
</div>

