<?php

$baseUrl = \EenmaalAndermaal\App::getApp()->getConfig()->get("website.url");
/** @var $this \EenmaalAndermaal\View\VeilingDetailView */
use \EenmaalAndermaal\View\Component\VeilingCollectionComponent;

?>

<div class="container veiling-detail-container">
    <div class="row"></div>
    <div class="row">
        <div class="col s12 white center">
            <h3 class="header left-align"><?= $this->veiling->titel ?>huehuehue</h3>
            <span class="left">Deze veiling is 2380482x bekeken</span>
        </div>
        <div class="col m8 s12">
            <div class="carousel carousel-slider center">
                <a class="carousel-item" href="#one!"><img src="https://lorempixel.com/800/400/food/1"></a>
                <a class="carousel-item" href="#two!"><img src="https://lorempixel.com/800/400/food/2"></a>
                <a class="carousel-item" href="#three!"><img src="https://lorempixel.com/800/400/food/3"></a>
                <a class="carousel-item" href="#four!"><img src="https://lorempixel.com/800/400/food/4"></a>
            </div>
            <div class="row">
                <div class="col s12 product-beschrijving">
                    <p class="left-align flow-text"><?= $this->veiling->beschrijving ?></p>
                </div>
                <div class="row"></div>
                <div class="row">
                    <div class="col s12">
                        <ul class="tabs">
                            <li class="tab col s3"><a class="active light-green-text" href="#details">Details</a></li>
                            <li class="tab col s3"><a class="light-green-text" href="#meer-info">Meer info</a></li>
                            <li class="tab col s3"><a class="light-green-text" href="#locatie">Locatie</a></li>
                            <li class="tab col s3"><a class="light-green-text" href="#verkoper">Verkoper</a></li>

                        </ul>
                    </div>
                    <div id="details" class="col s12">
                    </div>
                    <div id="meer-info" class="col s12">
                        <div class="col s12 extra-informatie">
                            <h3>Extra-informatie</h3>
                            <p class="left-align">Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de
                                16e eeuw,
                                toen een
                                onbekende drukker een zet haak met letters nam en ze doLorem Ipsum is de standaard
                                proeftekst in
                                deze
                                bedrijfstak sinds de 16e eeuw, toen een
                                onbekende drukker een zethaak met letters nam en ze do
                            </p>
                        </div>
                    </div>
                    <div id="locatie" class="col s12">
                        <div class="col s12 extra-informatie">
                            <h3>Locatie</h3>
                            <p class="left-align">Deze functie is tijdelijk niet beschikbaar.
                            </p>
                        </div>
                    </div>
                    <div id="verkoper" class="col s12">
                        <div class="col s12 verkoper">
                            <h3>Verkoper</h3>
                            <div class="row">
                                <div class="col s12 m12 l12">
                                    <b>Gebruikers informatie</b>
                                    <div class="divider"></div>
                                    <div class="row">
                                        <div class="col s6 m6 l6 bold">Voornaam</div>
                                        <div class="col s6 m6 l6">John</div>

                                        <div class="col s6 m6 l6 bold">Achternaam</div>
                                        <div class="col s6 m6 l6">Doe</div>

                                        <div class="col s6 m6 l6 bold">Gebruikersnaam</div>
                                        <div class="col s6 m6 l6">verkoper1</div>

                                        <div class="col s6 m6 l6 bold">Geslacht</div>
                                        <div class="col s6 m6 l6">Man</div>

                                        <div class="col s6 m6 l6 bold">Stad</div>
                                        <div class="col s6 m6 l6">Arnhem</div>

                                        <div class="col s6 m6 l6 bold">Land</div>
                                        <div class="col s6 m6 l6">Nederland</div>
                                    </div>

                                    <b>Contact informatie</b>
                                    <div class="divider"></div>
                                    <div class="row">
                                        <div class="col s6 m6 l6 bold">Email</div>
                                        <div class="col s6 m6 l6">johndoe@hotmail.nl</div>

                                        <div class="col s6 m6 l6 bold">Telefoonnummer</div>
                                        <div class="col s6 m6 l6">+31612345678</div>
                                    </div>

                                    <b>Reviews</b>
                                    <div class="divider"></div>
                                    <div class="row">
                                        <div class="col s6 m6 l6 bold">Aantal reviews</div>
                                        <div class="col s6 m6 l6">84</div>

                                        <div class="col s6 m6 l6 bold">Gemiddelde rating</div>
                                        <div class="col s6 m6 l6">4.1/5</div>
                                    </div>
                                    <button class="btn light-green">Bekijk profiel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col m4 s12">
            <div class="card no-margin green lighten-5">
                <div class="card-content">
                    <h3 class="center-align no-margin">01:43:50</h3>
                    <div class="row">
                        <form class="col s12">
                            <div class="row">
                                <div class="input-field col s6">
                                    <i class="material-icons prefix">euro_symbol</i>
                                    <input id="icon_prefix" type="text" class="validate">
                                    <label for="icon_prefix">Bod</label>
                                </div>
                                <div class="valign-wrapper">
                                    <button class="btn waves-effect waves-light ali" type="submit" name="action">Bod
                                        plaatsen
                                        <i class="material-icons right"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="row">
                        <div class="col l12 s12">
                            <div class="biedingen white">
                                <table class="">
                                    <thead>
                                    <tr>
                                        <th class="left">Gebruiker</th>
                                        <th>Bod</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php for ($i = 0; $i < 10; $i++) { ?>
                                        <tr>
                                            <td class="left">Steven Piedra</td>
                                            <td>€ 123,23</td>
                                        </tr>
                                    <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col l12 m12 s12">
            <h4>Gerelateerde veilingen</h4>
            <?=$this->renderComponent(new VeilingCollectionComponent($this->collection)) ?>
        </div>
    </div>
</div>