<?php

use EenmaalAndermaal\View\Component\AfstandFilterComponent;
use EenmaalAndermaal\View\Component\PrijsFilterComponent;
use EenmaalAndermaal\View\Component\VeilingCollectionComponent;
use EenmaalAndermaal\View\ZoekResultaatView;

/** @var ZoekResultaatView $this */

?>

<div class="row">
    <div class="col l3 m4 s12">
        <p class="flow-text">Filteren</p>
        <?= $this->renderComponent(new PrijsFilterComponent()) ?>
        <?= $this->renderComponent(new AfstandFilterComponent()) ?>
    </div>

    <div class="col l9 m6 s12">
        <div class="container">
            <p class="flow-text center-align">Zoekresultaten</p>
            <div class="row">
                <?= $this->renderComponent(new VeilingCollectionComponent($this->zoekresultaat)) ?>
            </div>
        </div>
    </div>
</div>