<?php
/** @var VeilingComponent $this */

use EenmaalAndermaal\View\Component\VeilingComponent;

$url = \EenmaalAndermaal\App::getApp()->getConfig()->get("website.url");
?>
    <div class="veiling card">
        <div class="card-image">
            <img src="<?= $url ?>">
        </div>
        <div class="card-content description">
            <span class="card-title black-text"><?= $this->item->titel ?></span>
            <p><?= $this->item->beschrijving ?></p>
        </div>
        <div class="card-content">
            <p class="veiling-countdown"><?= $this->item->beginTijd ?><span class="right">&euro;<?=$this->item->prijs / 100 ?></span></p>
        </div>
        <div class="card-action">
            <a class="btn light-green darken-2" href="<?= $url ?>veiling/<?= $this->item->nummer ?>">Bekijk veiling</a>
        </div>
    </div>