<?php
/** @var VeilingComponent $this */

use EenmaalAndermaal\Util\StringUtil as S;
use EenmaalAndermaal\View\Component\VeilingComponent;

$url = \EenmaalAndermaal\App::getApp()->getConfig()->get("website.url");
?>
<div class="veiling card" id="veilingcard-<?= $this->item->getIdentifier() ?>">
    <div class="card-image">
        <img class="materialboxed" data-caption="<?= $this->item->titel ?>"
             src="http://iproject21.icasites.nl/<?= $this->item->thumbnail ?>">
        <span class="card-title"><?= $this->item->titel ?></span>
    </div>
    <div class="card-content description">
        <p><?= strip_tags($this->item->beschrijvingKort) ?></p>
    </div>
    <div class="card-content">
        <p class="veiling-countdown"><span class="card-counter"
                                           data-value="<?= strtotime($this->item->eindDag . " " . $this->item->eindTijd) ?>"
                                           data-id="countdown-<?= $this->item->getIdentifier() ?>"
                                           data-parent="veilingcard-<?= $this->item->getIdentifier() ?>"
                                           id="countdown-<?= $this->item->getIdentifier() ?>"><?= date("H:m:s", strtotime($this->item->eindTijd)) ?></span><span
                    class="right"><?= S::euro($this->item->verkoopPrijs) ?></span></p>
    </div>
    <div class="card-action">
        <a class="btn light-green darken-2" href="<?= $url ?>veiling/<?= $this->item->nummer ?>">Bekijk veiling</a>
    </div>
</div>