<?php
/**
 * Created by PhpStorm.
 * User: arnol
 * Date: 17-5-2019
 * Time: 16:20
 */
?>

<div class="section"></div>
<div class="section"></div>
<center>
    <h5 class="light-green-text">EenmaalAndermaal <br> Login</h5>
    <div class="section"></div>

    <div class="container">
        <div class="z-depth-1 grey lighten-4 row"
             style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

            <form class="col s12" method="post">
                <div class='row'>
                    <div class='col s12'>
                    </div>
                </div>

                <div class='row'>
                    <div class='input-field col s12'>
                        <input class='validate' type="text" name='Gebruikersnaam' id='Gebruikersnaam'/>
                        <label for='Gebruikersnaam'>Gebruikersnaam</label>
                    </div>
                </div>

                <div class='row'>
                    <div class='input-field col s12'>
                        <input class='validate' type='password' name='password' id='password'/>
                        <label for='password'>Wachtwoord</label>
                    </div>
                    <label style='float: right;'>
                        <a class='pink-text' href='#!'><b>Wachtwoord vergeten?</b></a>
                    </label>
                </div>
                <br/>
                <div class='row'>
                    <button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect light-green'>
                        Login
                    </button>
                </div>
            </form>
        </div>
    </div>
    <a href="#!">Registreren</a>
    <div class="section"></div>
    <div class="section"></div>
</center>