<?php
/**
 * Created by PhpStorm.
 * User: arnol
 * Date: 17-5-2019
 * Time: 16:20
 */

use EenmaalAndermaal\App;
use EenmaalAndermaal\Services\UserService;

$url = App::getApp()->getConfig()->get("website.url");
?>

<?php if (!UserService::getInstance()->userLoggedIn()) { ?>
    <div class="row"></div>
    <div class="row"></div>
    <div class="center">
        <h5 class="light-green-text">EenmaalAndermaal <br> Login</h5>
        <div class="section"></div>

        <div class="container">
            <div class="row ">
                <form class="col s12 m8 offset-m2 l4 offset-l4 card light-green lighten-5" method="post">
                    <div class='row light-green lighten-5 card-content'>
                        <div class='col s12'>
                            <?php if (isset($this->error) && !empty($this->error)) { ?>
                                <p class="left-align red-text light-green lighten-3 z-depth-1"><?= $this->error ?></p>
                            <?php } ?>
                        </div>
                        <div class='input-field col s12'>
                            <input class='validate' type="text" name='gebruikersnaam' id='gebruikersnaam'
                                   value="<?= isset($this->post['gebruikersnaam']) ? $this->post['gebruikersnaam'] : "" ?>"/>
                            <label for='gebruikersnaam'>Gebruikersnaam</label>
                        </div>
                        <div class='input-field col s12'>
                            <input class='validate' type='password' name='wachtwoord' id='password'
                                   value="<?= isset($this->post['wachtwoord']) ? $this->post['wachtwoord'] : "" ?>"/>
                            <label for='password'>Wachtwoord</label>
                        </div>
                        <label style='float: right;'>
                            <a class='pink-text' href='<?= $url ?>wachtwoord-vergeten'><b>Wachtwoord vergeten?</b></a>
                        </label>
                    </div>
                    <br/>
                    <div class='row'>
                        <button type='submit' class='btn btn-large waves-effect light-green'>
                            Login
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <a href="<?= $url ?>registreren">Registreren</a>
        <div class="section"></div>
        <div class="section"></div>
    </div>
<?php } else { ?>
    <div class="container">
    <h1>Er ging iets fout..</h1>
        <p>U bent al ingelogd.</p>
    </div>
<?php } ?>
