<?php

use EenmaalAndermaal\View\Component\RubriekSideComponent;

?>
<div class="row">
    <div class="col l3 m12 s12">
        <?= $this->renderComponent(new RubriekSideComponent($this->rubriek, $this->activeId)); ?>
    </div>  
    <div class="col l9 m12 s12">
        <div class="row">
            <div class="col l12">
                <?= $this->renderComponent($this->breadCrumbComponent) ?>
            </div>
            <div class="col l12">
                <h2><?= isset($this->subRubriek) ? $this->subRubriek->naam : $this->rubriek->naam ?></h2>
                <p><?= isset($this->subRubriek) ? $this->subRubriek->beschrijving : $this->rubriek->beschrijving ?></p>
                <?= $this->renderComponent(new \EenmaalAndermaal\View\Component\VeilingCollectionComponent($this->collection)) ?>
            </div>
        </div>
    </div>
</div>