<?php

use EenmaalAndermaal\View\Component\RubriekSideComponent;

?>
<div class="row">
    <div class="col l3">
        <?= $this->renderComponent(new RubriekSideComponent($this->rubriek, $this->activeId)); ?>
    </div>
    <div class="col l9">
        <div class="container">
            <div class="row">
                <div class="col l12">
                    <h1>test jkaldjflaskfas hsdjafh asjkhasdjk hsdkjfash jhkdfjahsfjkashjk ashf kjashdf jk</h1>
                </div>
            </div>
        </div>
    </div>
</div>