<div class="container">
    <div class="row">
        <div class="col s12">
            <h5 class="center-align">Verkoop eenvoudig op EenmaalAndermaal</h5>
            <div class="row verkoper-cards">
                <div class="col s12 m12 l4">
                    <div class="card center">
                        <div class="card-image">
                            <i class="large material-icons">create</i>
                        </div>
                        <div class="card-content">
                            <span class="card-title">Direct registreren</span>
                            <p class="left-align">Binnen enkele minuten bent u geregistreerd en geverifieerd
                                als
                                verkoper
                                en kunt u beginnen met het aanbieden van uw veilingen!
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m12 l4">
                    <div class="card center">
                        <div class="card-image">
                            <i class="large material-icons">https</i>
                        </div>
                        <div class="card-content">
                            <span class="card-title">Veilig verkopen</span>
                            <p class="left-align">EenmaalAndermaal brengt kopers en verkopers bij elkaar en
                                hecht veel waarde aan
                                vertrouwen. Wij zijn niet betrokken bij de verdere verkoop. Deze ga je zelf
                                aan
                                met de koper. Daarom is het belangrijk dat je goed oplet met wie je handelt.

                            </p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m12 l4">
                    <div class="card center">
                        <div class="card-image">
                            <i class="large material-icons">attach_money</i>
                        </div>
                        <div class="card-content">
                            <span class="card-title">Snel verdienen</span>
                            <p class="left-align">Bepaal zelf je looptijd en startprijs. Wij zorgen dat
                                vraag en aanbod met elkaar
                                in contact komen zodat het snel verkocht kan worden!
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>