<?php
use EenmaalAndermaal\App;
$baseUrl = App::getApp()->getConfig()->get("website.url");
?>

<div class="container">
<div class="row">
    <h1>Privacy Statement EenmaalAndermaal</h1>
    <p class="flow-text">
    <blockquote>
    EenmaalAndermaal, gevestigd aan n.v.t.,<br> is verantwoordelijk voor de verwerking van persoonsgegevens zoals weergegeven in deze privacyverklaring.
    Contactgegevens:<br>
    http://iproject21.icasites.nl/<br>
    +31 037465829<br>
    Arnold Karels is de Functionaris Gegevensbescherming van EenmaalAndermaal<br>
    Hij/zij is te bereiken via<br> arnold.karels@outlook.com
    </blockquote>
    <h5>Persoonsgegevens die wij verwerken</h5>
    EenmaalAndermaal verwerkt uw persoonsgegevens doordat u gebruik maakt van onze diensten en/of omdat u deze zelf aan ons verstrekt.

    <h6>Hieronder vindt u een overzicht van de persoonsgegevens die wij verwerken:</h6>
    <blockquote>
    <ul>
        <li>- Voor- en achternaam</li>
        <li>- Geslacht</li>
        <li>- Geboortedatum</li>
        <li>- Adresgegevens</li>
        <li>- Telefoonnummer</li>
        <li>- E-mailadres</li>
        <li>- IP-adres</li>
        <li>- Overige persoonsgegevens die u actief verstrekt bijvoorbeeld door een profiel op deze website aan te maken, in correspondentie en telefonisch</li>
        <li>- Locatiegegevens</li>
        <li>- Gegevens over uw activiteiten op onze website</li>
    </ul>
    </blockquote>

    <h5>Bijzondere en/of gevoelige persoonsgegevens die wij verwerken</h5>
    <blockquote>
    Onze website en/of dienst heeft niet de intentie gegevens te verzamelen over websitebezoekers die jonger zijn dan 16 jaar.
    Tenzij ze toestemming hebben van ouders of voogd.
    We kunnen echter niet controleren of een bezoeker ouder dan 16 is.
    Wij raden ouders dan ook aan betrokken te zijn bij de online activiteiten van hun kinderen,
    om zo te voorkomen dat er gegevens over kinderen verzameld worden zonder ouderlijke toestemming.
    Als u er van overtuigd bent dat wij zonder die toestemming persoonlijke gegevens hebben verzameld over een minderjarige,
    neem dan contact met ons op via EenmaalAndermaal@gmail.com, dan verwijderen wij deze informatie.
    </blockquote>

    <h5>Met welk doel en op basis van welke grondslag wij persoonsgegevens verwerken</h5>
    <blockquote>
    EenmaalAndermaal verwerkt uw persoonsgegevens voor de volgende doelen:
    <ul>
        <li>- Het afhandelen van uw betaling</li>
        <li>- U te kunnen bellen of e-mailen indien dit nodig is om onze dienstverlening uit te kunnen voeren</li>
        <li>- U de mogelijkheid te bieden een account aan te maken</li>
        <li>- EenmaalAndermaal analyseert uw gedrag op de website om daarmee de website te verbeteren en het aanbod van producten en diensten af te stemmen op uw voorkeuren.</li<
    </ul>
    </blockquote>

    <h5>Geautomatiseerde besluitvorming</h5>

    <blockquote>
    EenmaalAndermaal neemt op basis van geautomatiseerde verwerkingen besluiten over zaken die (aanzienlijke) gevolgen kunnen hebben voor personen. Het gaat hier om besluiten die worden genomen door computerprogramma's of -systemen, zonder dat daar een mens (bijvoorbeeld een medewerker van EenmaalAndermaal) tussen zit. EenmaalAndermaal gebruikt de volgende computerprogramma's of -systemen:
    Recommandatie algoritme
    </blockquote>
    <h5>Hoe lang we persoonsgegevens bewaren</h5>
    <blockquote>
    EenmaalAndermaal bewaart uw persoonsgegevens niet langer dan strikt nodig is om de doelen te realiseren waarvoor uw gegevens worden verzameld.
     Wij hanteren de volgende bewaartermijnen voor de volgende (categorieën) van persoonsgegevens:<br>

    (Categorie) persoonsgegevens > zolang user account bestaat > De persoon gegevens worden bewaart voor het gebruiken van website locatie filters user reviews.<br>
    Personalia > zolang user account bestaat > Deze gegevens worden bewaard voor     het bepalen van de gebruikers voorkeuren<br>
    Gebruikers activiteit > zolang user account bestaat > Wij gebruiken de activiteiten om het gedrag van de gebruikers van de website bij te houden om hieruit mogelijke verbeter punten te halen voor het gebruik van de website.<br>
    </blockquote>


    <h5>Delen van persoonsgegevens met derden</h5>
    <blockquote>
    EenmaalAndermaal verstrekt uitsluitend aan derden en alleen als dit nodig is voor de uitvoering van onze overeenkomst met u of om te voldoen aan een wettelijke verplichting.
    </blockquote>

    <h5>Cookies, of vergelijkbare technieken, die wij gebruiken</h5>
    <blockquote>
    EenmaalAndermaal gebruikt functionele, analytische en tracking cookies. Een cookie is een klein tekstbestand dat bij het eerste bezoek aan deze website wordt opgeslagen in de browser van uw computer, tablet of smartphone. EenmaalAndermaal gebruikt cookies met een puur technische functionaliteit. Deze zorgen ervoor dat de website naar behoren werkt en dat bijvoorbeeld uw voorkeursinstellingen onthouden worden. Deze cookies worden ook gebruikt om de website goed te laten werken en deze te kunnen optimaliseren. Daarnaast plaatsen we cookies die uw surfgedrag bijhouden zodat we op maat gemaakte content en advertenties kunnen aanbieden.

    Bij uw eerste bezoek aan onze website hebben wij u al geïnformeerd over deze cookies en toestemming gevraagd voor het plaatsen ervan.

    U kunt zich afmelden voor cookies door uw internetbrowser zo in te stellen dat deze geen cookies meer opslaat. Daarnaast kunt u ook alle informatie die eerder is opgeslagen via de instellingen van uw browser verwijderen.

    Zie voor een toelichting: https://veiliginternetten.nl/themes/situatie/cookies-wat-zijn-het-en-wat-doe-ik-ermee/
    </blockquote>


    <h5>Gegevens inzien, aanpassen of verwijderen</h5>
    <blockquote>
    U heeft het recht om uw persoonsgegevens in te zien, te corrigeren of te verwijderen. Daarnaast heeft u het recht om uw eventuele toestemming voor de gegevensverwerking in te trekken of bezwaar te maken tegen de verwerking van uw persoonsgegevens door EenmaalAndermaal en heeft u het recht op gegevensoverdraagbaarheid. Dat betekent dat u bij ons een verzoek kunt indienen om de persoonsgegevens die wij van u beschikken in een computerbestand naar u of een ander, door u genoemde organisatie, te sturen.

    U kunt een verzoek tot inzage, correctie, verwijdering, gegevensoverdraging van uw persoonsgegevens of verzoek tot intrekking van uw toestemming of bezwaar op de verwerking van uw persoonsgegevens sturen naar EenmaalAndermaal@gmail.com.

    Om er zeker van te zijn dat het verzoek tot inzage door u is gedaan, vragen wij u een kopie van uw identiteitsbewijs met het verzoek mee te sturen. Maak in deze kopie uw pasfoto, MRZ (machine readable zone, de strook met nummers onderaan het paspoort), paspoortnummer en Burgerservicenummer (BSN) zwart. Dit ter bescherming van uw privacy. We reageren zo snel mogelijk, maar binnen vier weken, op uw verzoek.

    EenmaalAndermaal wil u er tevens op wijzen dat u de mogelijkheid heeft om een klacht in te dienen bij de nationale toezichthouder, de Autoriteit Persoonsgegevens. Dat kan via de volgende link: https://autoriteitpersoonsgegevens.nl/nl/contact-met-de-autoriteit-persoonsgegevens/tip-ons
    </blockquote>


    <h5>Hoe wij persoonsgegevens beveiligen</h5>
    <blockquote>
    EenmaalAndermaal neemt de bescherming van uw gegevens serieus en neemt passende maatregelen om misbruik, verlies, onbevoegde toegang, ongewenste openbaarmaking en ongeoorloofde wijziging tegen te gaan. Als u de indruk heeft dat uw gegevens niet goed beveiligd zijn of er aanwijzingen zijn van misbruik, neem dan contact op met onze klantenservice of via
    </blockquote>
    </p>
    </div>
 </div>