<?php use EenmaalAndermaal\View\Component\VeilingCollectionC;

?>
<div class="container">
    <h1>Aanbiedingen</h1>
    <?= $this->reginderComponent(new \EenmaalAndermaal\View\Component\VeilingCollectionComponent())
        [
            "name" => "Elektronica",
            "rubrieken" => [
                [
                    "name" => "Elektronica",
                    "icon" => "desktop_windows",
                    "rubrieken" => [
                        [
                            "name" => "laptop pc",
                            "id" => 10,
                        ],
                        [
                            "name" => "laptop mac",
                            "id" => 13,
                        ]
                    ]
                ],
                [
                    "name" => "Printers",
                    "icon" => "local_printshop",
                    "rubrieken" => [
                        [
                            "name" => "3D printer",
                            "id" => 12,
                        ],
                        [
                            "name" => "Inktjet",
                            "id" => 14,
                        ]
                    ]
                ]
            ]
        ], 13)) ?>
</div>

