<?php /** @var $this \EenmaalAndermaal\View\RegistratieView */

use EenmaalAndermaal\Services\UserService; ?>

<div class="container">
    <?php if (!UserService::getInstance()->userLoggedIn()) { ?>
        <div class="gebruiker-registratie">
            <div class="registratie-container z-depth-2">
                <div class="row">
                    <div class="row"></div>
                    <nav>
                        <div class="nav-wrapper light-green">
                            <span class="left title">Registreer een account</span>
                        </div>
                    </nav>
                </div>

                <?php
                if ($this->submit) {
                    if (count($this->errors)) { ?>
                        <div class="row">
                            <div class="col s12 m6 l4">
                                <div class="card red lighten-1">
                                    <div class="card-content">
                                        <span class="card-title">Er is iets fout gegaan</span>
                                        <ul>
                                            <?php foreach ($this->errors as $error) { ?>
                                                <li><?= $error ?></li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php }
                } ?>

                <form method="post" class="col m8 s12">
                    <h5>Persoonlijke gegevens</h5>
                    <div class="row">
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">contacts</i>
                            <input id="voornaam" name="voornaam" type="text" class="validate" required
                                   value="<?= isset($this->fields['voornaam']) ? $this->fields['voornaam'] : "" ?>">
                            <label for="voornaam">Voornaam</label>
                        </div>
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">contacts</i>
                            <input id="achternaam" name="achternaam" type="text" class="validate" required
                                   value="<?= isset($this->fields['achternaam']) ? $this->fields['achternaam'] : "" ?>">
                            <label for="achternaam">Achternaam</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">local_phone</i>
                            <input id="telefoonnummer" name="telefoonnummer" type="number" class="validate"
                                   maxlength="32"
                                   required
                                   value="<?= isset($this->fields['telefoonnummer']) ? $this->fields['telefoonnummer'] : "" ?>">
                            <label for="telefoonnummer">Telefoonnummer</label>
                        </div>
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">date_range</i>
                            <input id="geboortedatum" name="geboortedatum" type="text" class="datepicker validate"
                                   required>
                            <label for="geboortedatum">Geboortedatum</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">location_city</i>
                            <select name="land"
                                    id="land"
                                    tabindex="8" class="validate" required>
                                <option value="" <?= count($this->fields) ? "" : "selected" ?> disabled>Selecteer een land</option>
                                <?php foreach ($this->landen as $land) {
                                    /** @var \EenmaalAndermaal\Model\LandModel $land */
                                    ?>
                                    <option value="<?= $land->landcode ?>"
                                        <?= isset($this->fields['land']) && $land->landcode == $this->fields['land'] ? 'selected' : '' ?>
                                    ><?= $land->naam ?></option>
                                <?php } ?>
                            </select>
                            <label for="land">Land</label>
                        </div>
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">location_city</i>
                            <input id="stad" name="plaatsnaam" type="text" class="validate"
                                   value="<?= isset($this->fields['plaatsnaam']) ? $this->fields['plaatsnaam'] : "" ?>">
                            <label for="stad">Stad</label>
                        </div>

                    </div>
                    <div class="row">
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">home</i>
                            <input name="postcode" id="postcode" type="text" class="validate" maxlength="16"
                                   value="<?= isset($this->fields['postcode']) ? $this->fields['postcode'] : "" ?>">
                            <label for="postcode">Postcode</label>
                        </div>
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">home</i>
                            <input id="adres" type="text" name="adres" class="validate" required
                                   value="<?= isset($this->fields['adres']) ? $this->fields['adres'] : "" ?>">
                            <label for="adres">Adres</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">home</i>
                            <input id="adresaanvulling" type="text" name="adresAanvulling" class="validate"
                                   value="<?= isset($this->fields['adresaanvulling']) ? $this->fields['adresaanvulling'] : "" ?>">
                            <label for="adresaanvulling">Adres aanvulling</label>
                        </div>
                    </div>
                    <h5>Accountgegevens</h5>
                    <div class="row">
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">account_circle</i>
                            <input id="gebruikersnaam" type="text" class="validate" name="gebruikersnaam" required
                                   value="<?= isset($this->fields['gebruikersnaam']) ? $this->fields['gebruikersnaam'] : "" ?>">
                            <label for="gebruikersnaam">Gebruikersnaam</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">vpn_key</i>
                            <input id="wachtwoord" type="password" name="wachtwoord" class="validate" required
                                   value="<?= isset($this->fields['wachtwoord']) ? $this->fields['wachtwoord'] : "" ?>">
                            <label for="wachtwoord">Wachtwoord</label>
                        </div>
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">replay</i>
                            <input id="wachtwoord2" name="wachtwoord2" type="password" class="validate" required
                                   value="<?= isset($this->fields['wachtwoord2']) ? $this->fields['wachtwoord2'] : "" ?>">
                            <label for="wachtwoord2">Herhaal wachtwoord</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">email</i>
                            <input id="email" type="email" name="email" class="validate" required
                                   value="<?= isset($this->fields['email']) ? $this->fields['email'] : "" ?>">
                            <label for="email">Email</label>
                        </div>
                        <div class="input-field hoverable col m6 s12">
                            <i class="material-icons prefix">email</i>
                            <input id="email2" name="email2" type="email" class="validate" required
                                   value="<?= isset($this->fields['email2']) ? $this->fields['email2'] : "" ?>">
                            <label for="email2">Herhaal email</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col m6 s12">
                            <select name="vraag"
                                    id="vraag"
                                    tabindex="8" class="validate" required>
                                <option value="" selected disabled>Selecteer een geheime vraag en voer een antwoord in.
                                </option>
                                <?php foreach ($this->vragen as $vraag) {
                                    /** @var \EenmaalAndermaal\Model\VraagModel $vraag */
                                    ?>
                                    <option value="<?= $vraag->nummer ?>"><?= $vraag->vraag ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="input-field col m6 s12">
                            <input type="text" name="antwoordvraag" id="geheime-vraag-antwoord"
                                   value="<?= isset($this->fields['antwoordvraag']) ? $this->fields['antwoordvraag'] : "" ?>"
                                   required/>
                            <label for="geheime-vraag-antwoord">Antwoord</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col m12 s12">
                            <p>
                                <label>
                                    <input type="checkbox" required class="validate filled-in" id="TOS"/>
                                    <span>Ik accepteer de <a class="top-link modal-trigger" data-target="terms"
                                                             href="#terms">voorwaarden van de overeenkomst</a></span>

                                </label>
                            </p>
                            <p>
                                <label>
                                    <input type="checkbox" name="melding" class="filled-in" checked="checked" required/>
                                    <span>Ik begrijp dat updates van veilingen via email plaats vind.</span>
                                </label>
                            </p>
                        </div>
                        <div class="col m12 s12">
                            <input type="hidden" name="form_submitted" value="1">
                            <button class="waves-effect waves-light btn-large right hoverable light-green">
                                <i class="large material-icons right">done</i>Registreren
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    <?php } else { ?>
        <h1>Er ging iets fout..</h1>
        <p>Momenteel bent u nog ingelogd op een bestaand account. Log alstublieft eerst uit. Daarna kan een ander account aangemaakt worden.</p>
    <?php } ?>
</div>
<div id="terms" class="modal">
    <div class="modal-content">
        <h4>Voorwaarden van de overeenkomst</h4>
        <p id="TOStext"></p>
    </div>
    <div class="modal-footer">
        <a href="#!" id="agree" class="modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
</div>

